apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "a033c466eb00e4ad4944fbdb9601e68c-1925513909.ap-northeast-2.elb.amazonaws.com"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "a63ce823295da40559f25beb8ce48147-1966972725.ap-northeast-2.elb.amazonaws.com"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka3
spec:
  replicas: 1
  selector:
    app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - name: kafka3
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "aedac70e74b6e44eb831a820b2b3c1e0-68828054.ap-northeast-2.elb.amazonaws.com"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181

