apiVersion: v1
kind: Service
metadata:
  name: kaf1
spec:
  type: LoadBalancer
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka1
---
apiVersion: v1
kind: Service
metadata:
  name: kaf2
spec:
  type: LoadBalancer
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka2

---
apiVersion: v1
kind: Service
metadata:
  name: kaf3
spec:
  type: LoadBalancer
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka3
